#
# Makefile for the CPU
#
TOP_DIR			?= $(shell pwd)/..
include $(TOP_DIR)/config.mk

obj-y	:=	cache.o
obj-y 	+= strcmp.o
obj-y 	+= strcpy.o
#obj-y 	+= string_copy.o
obj-y 	+= mmu.o

include $(TOP_DIR)/common.mk
