#
# Makefile for the UART.
#
TOP_DIR                     ?= $(shell pwd)/../..
include $(TOP_DIR)/config.mk


obj-y							:= portme_ftuart010.o ftuart010.o ftuart010_test.o


include $(TOP_DIR)/common.mk

