#
# Makefile for the drivers
#
TOP_DIR			?= $(shell pwd)/../..
include $(TOP_DIR)/config.mk

obj-y	:=	ftlcd210.o panel.o ftlcd210-OSD.o font.o panel.o \
animation.o color.o colorbar.o cursor.o \
PiP.o Pip_PoP_lib.o PoP.o register_test.o scalar.o STN_CSTN.o VBI.o virtual_screen.o \
portme_ftlcdc210.o


	
include $(TOP_DIR)/common.mk
