/*
 *  linux/arch/arm/mach-faraday/platform-a600/spec.c
 *
 *  Faraday Platform Specification  (Automatically generated by "autospec", do not edit)
 *
 *  Copyright (C) 2013 Faraday Corp. (http://www.faraday-tech.com)
 *
 *  Platform Hierarchy :
 *
 *    A600
 *     +- CPU_CA9MP  (0)
 *     +- ERAM_FTEMC030  (0)
 *     +- LCD_FTLCDC210  (0)
 *     +- DMAC_FTDMAC030  (0)
 *     +- DMAC_FTDMAC030  (1)
 *     +- RAM_FTDMAC030  (0)
 *     +- RAM_FTDMAC030  (1)
 *     +- RAM_FTDMAC030  (2)
 *     +- DDRC_FTDDR440  (0)
 *     +- SDC_FTSDC021  (0)
 *     +- SPI_FTSPI020  (0)
 *     +- GPIO_FTGPIO010  (0)
 *     +- IIC_FTIIC010  (0)
 *     +- IIC_FTIIC010  (1)
 *     +- UART_FTUART010  (0)
 *     +- UART_FTUART010  (1)
 *     +- UART_FTUART010  (2)
 *     +- SSP_FTSSP010  (0)
 *     +- SSP_FTSSP010  (1)
 *     +- SSP_FTSSP010  (2)
 *     +- SCU_FTSCU100  (0)
 *     +- TIMER_FTPWMTMR010  (0)
 *     +- WDT_FTWDT011  (0)
 */


//SoFia: #include <linux/config.h>
//SoFia: #include <linux/init.h>
//SoFia: #include <linux/module.h>

//SoFia: #include <asm/mach/map.h>
//SoFia: #include <asm/sizes.h>

#include "spec.h"  //SoFia

/*
 * Interrrupt numbers
 */


/* LCD */
const unsigned char LCD_FTLCDC210_irq[LCD_FTLCDC210_COUNT] = {
     LCD_FTLCDC210_0_IRQ
};

/* DMAC */
const unsigned char DMAC_FTDMAC030_irq[DMAC_FTDMAC030_COUNT][DMAC_FTDMAC030_IRQ_COUNT] = {
    { DMAC_FTDMAC030_0_IRQ0 },
    { DMAC_FTDMAC030_1_IRQ0 }
};

/* SDC */
const unsigned char SDC_FTSDC021_irq[SDC_FTSDC021_COUNT] = {
     SDC_FTSDC021_IRQ,
     SDC_FTSDC021_1_IRQ
};

/* SPI */
const unsigned char SPI_FTSPI020_irq[SPI_FTSPI020_COUNT] = {
     SPI_FTSPI020_0_IRQ
};

/* GPIO */
const unsigned char GPIO_FTGPIO010_irq[GPIO_FTGPIO010_COUNT] = {
     GPIO_FTGPIO010_0_IRQ
};

/* IIC */
const unsigned char IIC_FTIIC010_irq[IIC_FTIIC010_COUNT] = {
     IIC_FTIIC010_0_IRQ,
     IIC_FTIIC010_1_IRQ,
	 IIC_FTIIC010_2_IRQ,
	 IIC_FTIIC010_3_IRQ
};

/* UART */
const unsigned char UART_FTUART010_irq[UART_FTUART010_COUNT] = {
     UART_FTUART010_0_IRQ,
     UART_FTUART010_1_IRQ,
     UART_FTUART010_2_IRQ,
     UART_FTUART010_3_IRQ	 
};

/* SSP */
const unsigned char SSP_FTSSP010_irq[SSP_FTSSP010_COUNT] = {
     SSP_FTSSP010_0_IRQ,
     SSP_FTSSP010_1_IRQ,
     SSP_FTSSP010_2_IRQ
};

/* SCU */
const unsigned char SCU_FTSCU100_irq[SCU_FTSCU100_COUNT] = {
     SCU_FTSCU100_0_IRQ
};

/* TIMER */
const unsigned char TIMER_FTPWMTMR010_irq[TIMER_FTPWMTMR010_COUNT][TIMER_FTPWMTMR010_IRQ_COUNT] = {
    { TIMER_FTPWMTMR010_0_IRQ0, TIMER_FTPWMTMR010_IRQ1, TIMER_FTPWMTMR010_IRQ2, TIMER_FTPWMTMR010_IRQ3, TIMER_FTPWMTMR010_IRQ4, TIMER_FTPWMTMR010_IRQ5, TIMER_FTPWMTMR010_IRQ6, TIMER_FTPWMTMR010_IRQ7 },
    { TIMER_FTPWMTMR010_1_IRQ0, TIMER_FTPWMTMR010_1_IRQ1, TIMER_FTPWMTMR010_1_IRQ2, TIMER_FTPWMTMR010_1_IRQ3, TIMER_FTPWMTMR010_1_IRQ4, TIMER_FTPWMTMR010_1_IRQ5, TIMER_FTPWMTMR010_1_IRQ6, TIMER_FTPWMTMR010_1_IRQ7 }
};

/* WDT */
const unsigned char WDT_FTWDT011_irq[WDT_FTWDT011_COUNT] = {
     WDT_FTWDT011_0_IRQ,
     WDT_FTWDT011_1_IRQ
};

/*
 * Base addresses
 */


/* CPU */
const unsigned CPU_MEM_pa_base[CPU_MEM_PA_COUNT] = {
     CPU_MEM_0_PA_BASE
};
const unsigned CPU_MEM_pa_limit[CPU_MEM_PA_COUNT] = {
     CPU_MEM_0_PA_LIMIT
};
const unsigned CPU_MEM_pa_size[CPU_MEM_PA_COUNT] = {
     CPU_MEM_0_PA_SIZE
};

/* ERAM */
const unsigned ERAM_FTEMC030_pa_base[ERAM_FTEMC030_COUNT] = {
     ERAM_FTEMC030_0_PA_BASE
};
const unsigned ERAM_FTEMC030_pa_limit[ERAM_FTEMC030_COUNT] = {
     ERAM_FTEMC030_0_PA_LIMIT
};
const unsigned ERAM_FTEMC030_pa_size[ERAM_FTEMC030_COUNT] = {
     ERAM_FTEMC030_0_PA_SIZE
};

/* LCD */
const unsigned LCD_FTLCDC210_pa_base[LCD_FTLCDC210_COUNT] = {
     LCD_FTLCDC210_0_PA_BASE
};
const unsigned LCD_FTLCDC210_pa_limit[LCD_FTLCDC210_COUNT] = {
     LCD_FTLCDC210_0_PA_LIMIT
};
const unsigned LCD_FTLCDC210_pa_size[LCD_FTLCDC210_COUNT] = {
     LCD_FTLCDC210_0_PA_SIZE
};

/* DMAC */
const unsigned DMAC_FTDMAC030_pa_base[DMAC_FTDMAC030_COUNT] = {
     DMAC_FTDMAC030_0_PA_BASE,
     DMAC_FTDMAC030_1_PA_BASE
};
const unsigned DMAC_FTDMAC030_pa_limit[DMAC_FTDMAC030_COUNT] = {
     DMAC_FTDMAC030_0_PA_LIMIT,
     DMAC_FTDMAC030_1_PA_LIMIT
};
const unsigned DMAC_FTDMAC030_pa_size[DMAC_FTDMAC030_COUNT] = {
     DMAC_FTDMAC030_0_PA_SIZE,
     DMAC_FTDMAC030_1_PA_SIZE
};

/* RAM */
const unsigned RAM_FTDMAC030_pa_base[RAM_FTDMAC030_COUNT] = {
     RAM_FTDMAC030_0_PA_BASE,
     RAM_FTDMAC030_1_PA_BASE
};
const unsigned RAM_FTDMAC030_pa_limit[RAM_FTDMAC030_COUNT] = {
     RAM_FTDMAC030_0_PA_LIMIT,
     RAM_FTDMAC030_1_PA_LIMIT
};
const unsigned RAM_FTDMAC030_pa_size[RAM_FTDMAC030_COUNT] = {
     RAM_FTDMAC030_0_PA_SIZE,
     RAM_FTDMAC030_1_PA_SIZE
};

/* DDRC */
const unsigned DDRC_FTDDR440_pa_base[DDRC_FTDDR440_COUNT] = {
     DDRC_FTDDR440_0_PA_BASE
};
const unsigned DDRC_FTDDR3030_pa_limit[DDRC_FTDDR440_COUNT] = {
     DDRC_FTDDR440_0_PA_LIMIT
};
const unsigned DDRC_FTDDR3030_pa_size[DDRC_FTDDR440_COUNT] = {
     DDRC_FTDDR440_0_PA_SIZE
};

/* SDC */
const unsigned SDC_FTSDC021_pa_base[SDC_FTSDC021_COUNT] = {
     SDC_FTSDC021_0_PA_BASE
};
const unsigned SDC_FTSDC021_pa_limit[SDC_FTSDC021_COUNT] = {
     SDC_FTSDC021_0_PA_LIMIT
};
const unsigned SDC_FTSDC021_pa_size[SDC_FTSDC021_COUNT] = {
     SDC_FTSDC021_0_PA_SIZE
};

/* SPI */
const unsigned SPI_FTSPI020_pa_base[SPI_FTSPI020_COUNT] = {
     SPI_FTSPI020_0_PA_BASE
};
const unsigned SPI_FTSPI020_pa_limit[SPI_FTSPI020_COUNT] = {
     SPI_FTSPI020_0_PA_LIMIT
};
const unsigned SPI_FTSPI020_pa_size[SPI_FTSPI020_COUNT] = {
     SPI_FTSPI020_0_PA_SIZE
};

/* GPIO */
const unsigned GPIO_FTGPIO010_pa_base[GPIO_FTGPIO010_COUNT] = {
     GPIO_FTGPIO010_0_PA_BASE
};
const unsigned GPIO_FTGPIO010_pa_limit[GPIO_FTGPIO010_COUNT] = {
     GPIO_FTGPIO010_0_PA_LIMIT
};
const unsigned GPIO_FTGPIO010_pa_size[GPIO_FTGPIO010_COUNT] = {
     GPIO_FTGPIO010_0_PA_SIZE
};

/* IIC */
const unsigned IIC_FTIIC010_pa_base[IIC_FTIIC010_COUNT] = {
     IIC_FTIIC010_0_PA_BASE,
     IIC_FTIIC010_1_PA_BASE,
	 IIC_FTIIC010_2_PA_BASE,
	 IIC_FTIIC010_3_PA_BASE
};
const unsigned IIC_FTIIC010_pa_limit[IIC_FTIIC010_COUNT] = {
     IIC_FTIIC010_0_PA_LIMIT,
     IIC_FTIIC010_1_PA_LIMIT,
	 IIC_FTIIC010_2_PA_LIMIT,
	 IIC_FTIIC010_3_PA_LIMIT
};
const unsigned IIC_FTIIC010_pa_size[IIC_FTIIC010_COUNT] = {
     IIC_FTIIC010_0_PA_SIZE,
     IIC_FTIIC010_1_PA_SIZE,
	 IIC_FTIIC010_2_PA_SIZE,
	 IIC_FTIIC010_3_PA_SIZE
};

/* UART */
const unsigned UART_FTUART010_pa_base[UART_FTUART010_COUNT] = {
     UART_FTUART010_0_PA_BASE,
     UART_FTUART010_1_PA_BASE,
     UART_FTUART010_2_PA_BASE,
     UART_FTUART010_3_PA_BASE	 
};
const unsigned UART_FTUART010_pa_limit[UART_FTUART010_COUNT] = {
     UART_FTUART010_0_PA_LIMIT,
     UART_FTUART010_1_PA_LIMIT,
     UART_FTUART010_2_PA_LIMIT,
     UART_FTUART010_3_PA_LIMIT	 
};
const unsigned UART_FTUART010_pa_size[UART_FTUART010_COUNT] = {
     UART_FTUART010_0_PA_SIZE,
     UART_FTUART010_1_PA_SIZE,
     UART_FTUART010_2_PA_SIZE,
     UART_FTUART010_3_PA_SIZE
};

/* SSP */
const unsigned SSP_FTSSP010_pa_base[SSP_FTSSP010_COUNT] = {
     SSP_FTSSP010_0_PA_BASE,
     SSP_FTSSP010_1_PA_BASE,
     SSP_FTSSP010_2_PA_BASE
};
const unsigned SSP_FTSSP010_pa_limit[SSP_FTSSP010_COUNT] = {
     SSP_FTSSP010_0_PA_LIMIT,
     SSP_FTSSP010_1_PA_LIMIT,
     SSP_FTSSP010_2_PA_LIMIT
};
const unsigned SSP_FTSSP010_pa_size[SSP_FTSSP010_COUNT] = {
     SSP_FTSSP010_0_PA_SIZE,
     SSP_FTSSP010_1_PA_SIZE,
     SSP_FTSSP010_2_PA_SIZE
};

/* SCU */
const unsigned SCU_FTSCU100_pa_base[SCU_FTSCU100_COUNT] = {
     SCU_FTSCU100_0_PA_BASE
};
const unsigned SCU_FTSCU100_pa_limit[SCU_FTSCU100_COUNT] = {
     SCU_FTSCU100_0_PA_LIMIT
};
const unsigned SCU_FTSCU100_pa_size[SCU_FTSCU100_COUNT] = {
     SCU_FTSCU100_0_PA_SIZE
};

/* TIMER */
const unsigned TIMER_FTPWMTMR010_pa_base[TIMER_FTPWMTMR010_COUNT] = {
     TIMER_FTPWMTMR010_0_PA_BASE
};
const unsigned TIMER_FTPWMTMR010_pa_limit[TIMER_FTPWMTMR010_COUNT] = {
     TIMER_FTPWMTMR010_0_PA_LIMIT
};
const unsigned TIMER_FTPWMTMR010_pa_size[TIMER_FTPWMTMR010_COUNT] = {
     TIMER_FTPWMTMR010_0_PA_SIZE
};

/* WDT */
const unsigned WDT_FTWDT011_pa_base[WDT_FTWDT011_COUNT] = {
     WDT_FTWDT011_0_PA_BASE,
     WDT_FTWDT011_1_PA_BASE
};
const unsigned WDT_FTWDT011_pa_limit[WDT_FTWDT011_COUNT] = {
     WDT_FTWDT011_0_PA_LIMIT,
     WDT_FTWDT011_1_PA_LIMIT
};
const unsigned WDT_FTWDT011_pa_size[WDT_FTWDT011_COUNT] = {
     WDT_FTWDT011_0_PA_SIZE,
     WDT_FTWDT011_1_PA_SIZE
};

/* GMAC */
const unsigned GMAC_FTGMAC030_pa_base[GMAC_FTGMAC030_PA_COUNT] = {
     GMAC_FTGMAC030_0_PA_BASE,
     GMAC_FTGMAC030_1_PA_BASE
};

/*
 * Platform Initialization Information
 */

/*SoFia: const struct map_desc platform_io_desc[PLATFORM_IO_DESC_NR] __initdata = {
};*/

/*
 * Interrupt Dispatch Tables, for both FIQ and IRQ
 */

/* const interrupt_dispatch_function *fiq_dispatch_table[32]; */

/* const interrupt_dispatch_function *irq_dispatch_table[32]; */


/*
 * Export All Symbols
 */

/*
 * Interrrupt numbers
 */

/* LCD */
//SoFia: EXPORT_SYMBOL( LCD_FTLCDC210_irq );
/* DMAC */
//SoFia: EXPORT_SYMBOL( DMAC_FTDMAC030_irq );
/* SDC */
//SoFia: EXPORT_SYMBOL( SDC_FTSDC021_irq );
/* SPI */
//SoFia: EXPORT_SYMBOL( SPI_FTSPI020_irq );
/* GPIO */
//SoFia: EXPORT_SYMBOL( GPIO_FTGPIO010_irq );
/* IIC */
//SoFia: EXPORT_SYMBOL( IIC_FTIIC010_irq );
/* UART */
//SoFia: EXPORT_SYMBOL( UART_FTUART010_irq );
/* SSP */
//SoFia: EXPORT_SYMBOL( SSP_FTSSP010_irq );
/* SCU */
//SoFia: EXPORT_SYMBOL( SCU_FTSCU100_irq );
/* TIMER */
//SoFia: EXPORT_SYMBOL( TIMER_FTPWMTMR010_irq );
/* WDT */
//SoFia: EXPORT_SYMBOL( WDT_FTWDT011_irq );

/*
 * Base addresses
 */

/* CPU */
//SoFia: EXPORT_SYMBOL( CPU_MEM_pa_base );
//SoFia: EXPORT_SYMBOL( CPU_MEM_pa_limit );
//SoFia: EXPORT_SYMBOL( CPU_MEM_pa_size );
/* ERAM */
//SoFia: EXPORT_SYMBOL( ERAM_FTEMC030_pa_base );
//SoFia: EXPORT_SYMBOL( ERAM_FTEMC030_pa_limit );
//SoFia: EXPORT_SYMBOL( ERAM_FTEMC030_pa_size );
/* LCD */
//SoFia: EXPORT_SYMBOL( LCD_FTLCDC210_pa_base );
//SoFia: EXPORT_SYMBOL( LCD_FTLCDC210_pa_limit );
//SoFia: EXPORT_SYMBOL( LCD_FTLCDC210_pa_size );
/* DMAC */
//SoFia: EXPORT_SYMBOL( DMAC_FTDMAC030_pa_base );
//SoFia: EXPORT_SYMBOL( DMAC_FTDMAC030_pa_limit );
//SoFia: EXPORT_SYMBOL( DMAC_FTDMAC030_pa_size );
/* RAM */
//SoFia: EXPORT_SYMBOL( RAM_FTDMAC030_pa_base );
//SoFia: EXPORT_SYMBOL( RAM_FTDMAC030_pa_limit );
//SoFia: EXPORT_SYMBOL( RAM_FTDMAC030_pa_size );
/* DDRC */
//SoFia: EXPORT_SYMBOL( DDRC_FTDDR440_pa_base );
//SoFia: EXPORT_SYMBOL( DDRC_FTDDR440_pa_limit );
//SoFia: EXPORT_SYMBOL( DDRC_FTDDR440_pa_size );
/* SDC */
//SoFia: EXPORT_SYMBOL( SDC_FTSDC021_pa_base );
//SoFia: EXPORT_SYMBOL( SDC_FTSDC021_pa_limit );
//SoFia: EXPORT_SYMBOL( SDC_FTSDC021_pa_size );
/* SPI */
//SoFia: EXPORT_SYMBOL( SPI_FTSPI020_pa_base );
//SoFia: EXPORT_SYMBOL( SPI_FTSPI020_pa_limit );
//SoFia: EXPORT_SYMBOL( SPI_FTSPI020_pa_size );
/* GPIO */
//SoFia: EXPORT_SYMBOL( GPIO_FTGPIO010_pa_base );
//SoFia: EXPORT_SYMBOL( GPIO_FTGPIO010_pa_limit );
//SoFia: EXPORT_SYMBOL( GPIO_FTGPIO010_pa_size );
/* IIC */
//SoFia: EXPORT_SYMBOL( IIC_FTIIC010_pa_base );
//SoFia: EXPORT_SYMBOL( IIC_FTIIC010_pa_limit );
//SoFia: EXPORT_SYMBOL( IIC_FTIIC010_pa_size );
/* UART */
//SoFia: EXPORT_SYMBOL( UART_FTUART010_pa_base );
//SoFia: EXPORT_SYMBOL( UART_FTUART010_pa_limit );
//SoFia: EXPORT_SYMBOL( UART_FTUART010_pa_size );
/* SSP */
//SoFia: EXPORT_SYMBOL( SSP_FTSSP010_pa_base );
//SoFia: EXPORT_SYMBOL( SSP_FTSSP010_pa_limit );
//SoFia: EXPORT_SYMBOL( SSP_FTSSP010_pa_size );
/* SCU */
//SoFia: EXPORT_SYMBOL( SCU_FTSCU100_pa_base );
//SoFia: EXPORT_SYMBOL( SCU_FTSCU100_pa_limit );
//SoFia: EXPORT_SYMBOL( SCU_FTSCU100_pa_size );
/* TIMER */
//SoFia: EXPORT_SYMBOL( TIMER_FTPWMTMR010_pa_base );
//SoFia: EXPORT_SYMBOL( TIMER_FTPWMTMR010_pa_limit );
//SoFia: EXPORT_SYMBOL( TIMER_FTPWMTMR010_pa_size );
/* WDT */
//SoFia: EXPORT_SYMBOL( WDT_FTWDT011_pa_base );
//SoFia: EXPORT_SYMBOL( WDT_FTWDT011_pa_limit );
//SoFia: EXPORT_SYMBOL( WDT_FTWDT011_pa_size );

/*
 * Interrupt Dispatch Tables, for both FIQ and IRQ
 */

